//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInfo
    {
        public int CarID { get; set; }
        public string VendorInfoID { get; set; }
        public string RegNo { get; set; }
        public string Manufacturer { get; set; }
        public string modelNumber { get; set; }
        public int Capacity { get; set; }
        public Nullable<int> Doors { get; set; }
        public string Transmission { get; set; }
        public Nullable<bool> AC { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
