//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Demo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class HallInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HallInfo()
        {
            this.EventTypes = new HashSet<EventType>();
            this.HallActivities = new HashSet<HallActivity>();
            this.HallFacilities = new HashSet<HallFacility>();
            this.HallTypes = new HashSet<HallType>();
        }
    
        public int HallInfoID { get; set; }
        public string VendorInfoID { get; set; }
        public string HallName { get; set; }
        public System.Data.Entity.Spatial.DbGeography HallMapLocation { get; set; }
        public string HallDescription { get; set; }
        public string HallShortDescription { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual HallAddress HallAddress { get; set; }
        public virtual HallCapacity HallCapacity { get; set; }
        public virtual MyHallPricing MyHallPricing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventType> EventTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HallActivity> HallActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HallFacility> HallFacilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HallType> HallTypes { get; set; }

        [NotMapped]
        public IEnumerable<int> HallTypeSelectedIDs { get; set; }

        [NotMapped]
        public IEnumerable<int> HallEventTypeSelectedIDs { get; set; }

        [NotMapped]
        public IEnumerable<int> HallActivitiesSelectedIDs { get; set; }

        [NotMapped]
        public IEnumerable<int> HallFacilitySelectedIDs { get; set; }
    }
}
