//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HallCapacity
    {
        public int HallInfoID { get; set; }
        public Nullable<int> StandingCapacity { get; set; }
        public Nullable<int> Seated { get; set; }
        public Nullable<int> ClassRoomCapacity { get; set; }
        public Nullable<int> ThreatreCapacity { get; set; }
        public Nullable<int> BanquetCapacity { get; set; }
        public Nullable<int> ConferanceCapacity { get; set; }
        public Nullable<int> UShapeCapacity { get; set; }
        public string AdditionalInfoCapacity { get; set; }
        public Nullable<int> FloorArea { get; set; }
    
        public virtual HallInfo HallInfo { get; set; }
    }
}
