//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Demo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Taqreeb_FYPEntities : DbContext
    {
        public Taqreeb_FYPEntities()
            : base("name=Taqreeb_FYPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<HallActivity> HallActivities { get; set; }
        public virtual DbSet<HallAddress> HallAddresses { get; set; }
        public virtual DbSet<HallCapacity> HallCapacities { get; set; }
        public virtual DbSet<HallFacility> HallFacilities { get; set; }
        public virtual DbSet<HallInfo> HallInfoes { get; set; }
        public virtual DbSet<HallType> HallTypes { get; set; }
        public virtual DbSet<ImageDemo> ImageDemoes { get; set; }
        public virtual DbSet<MyHallPricing> MyHallPricings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<VendorAddress> VendorAddresses { get; set; }
        public virtual DbSet<CarInfo> CarInfoes { get; set; }
    }
}
